django-alessandria/alessandria/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from alessandria import views
from alessandria import ajax


app_name = "alessandria"

urlpatterns = [
    path("", views.HomeView.as_view(), name='home'),
    # /alessandria/login
    path("login", views.LoginView.as_view(), name='login'),
    path("logout", views.LogoutView.as_view(), name='logout'),
    path("reader_borrow/add/", views.ReaderBorrowCreateView.as_view(), name='reader_borrow_add'),
    path("reader_borrow/<int:pk>/", views.ReaderBorrowUpdateView.as_view(), name='reader_borrow_update'),
    path("reader_borrow/list/", views.ReaderBorrowListView.as_view(), name='reader_borrow_list'),
    path("reader_borrow/list/<str:display>/", views.ReaderBorrowListView.as_view(), name='reader_borrow_list'),
    path("reader_borrow/<int:pk>/delete/", views.ReaderBorrowDeleteView.as_view(), name='reader_borrow_delete'),
    path("reader/add/", views.ReaderCreateView.as_view(), name='reader_add'),
    path("reader/<int:pk>/", views.ReaderUpdateView.as_view(), name='reader_update'),
    path("reader/list/", views.ReaderListView.as_view(), name='reader_list'),
    path("reader/<int:pk>/delete/", views.ReaderDeleteView.as_view(), name='reader_delete'),
    path("reader/<int:pk>/disable/", views.ReaderDisableView.as_view(), name='reader_disable'),
    path("reader/<int:pk>/enable/", views.ReaderEnableView.as_view(), name='reader_enable'),

    path("author/add/", views.AuthorCreateView.as_view(), name='author_add'),
    path("author/add/<str:redirect_to_book>/", views.AuthorCreateView.as_view(), name='author_add'),
    path("author/<int:pk>/", views.AuthorUpdateView.as_view(), name='author_update'),
    path("author/<int:pk>/delete/", views.AuthorDeleteView.as_view(), name='author_delete'),
    path("author/list/", views.AuthorListView.as_view(), name='author_list'),

    path("publisher/add/", views.PublisherCreateView.as_view(), name='publisher_add'),
    path("publisher/add/<str:redirect_to_book>/", views.PublisherCreateView.as_view(), name='publisher_add'),
    
    path("publisher/<int:pk>/", views.PublisherUpdateView.as_view(), name='publisher_update'),
    path("publisher/<int:pk>/delete/", views.PublisherDeleteView.as_view(), name='publisher_delete'),
    path("publisher/list/", views.PublisherListView.as_view(), name='publisher_list'),
    path("publisher/<int:publisher_id>/books/", views.book_list_by_publisher, name='book_list_by_publisher'),

    path("book/add/", views.BookCreateView.as_view(), name='book_add'),
    path("book/add/<str:from_external_page>/", views.BookCreateView.as_view(), name='book_add'),
    path("book/<int:pk>/", views.BookUpdateView.as_view(), name='book_update'),
    path("book/<int:pk>/delete/", views.BookDeleteView.as_view(), name='book_delete'),
    path("book/list/", views.BookListView.as_view(), name='book_list'),
    path("book/no_copy_list/", views.BookNoCopyListView.as_view(), name='book_no_copy_list'),
    path("book/taken_away_list/", views.BookTakenAwayListView.as_view(), name='book_taken_away_list'),
    path("book/save_book_form_to_session/<str:dest_url>/", views.save_book_form_to_session, name='save_book_form_to_session'),
    path("book/isbn/import/", views.BookIsbnImportView.as_view(), name='book_isbn_import'),

    path("bookcopy/add/<int:book_id>/", views.BookCopyCreateView.as_view(), name='bookcopy_add'),
    path("bookcopy/<int:pk>/", views.BookCopyUpdateView.as_view(), name='bookcopy_update'),
    path("bookcopy/<int:pk>/disable/", views.BookCopyDisableView.as_view(), name='bookcopy_disable'),
    path("bookcopy/<int:pk>/delete/", views.BookCopyDeleteView.as_view(), name='bookcopy_delete'),

    path("statistics/borrowings/", views.StatisticsBorrowingsView.as_view(), name='statistics_borrowings'),
    path("statistics/readers/", views.StatisticsReadersView.as_view(), name='statistics_readers'),
    path("statistics/books_collections/", views.StatisticsBooksCollectionsView.as_view(), name='statistics_books_collections'),

    path("ajax/get/book_sub_categories/?", ajax.get_book_sub_categories, name='get_book_sub_categories'),
]

django-alessandria/alessandria/forms.py
import datetime

from django import forms
from django.utils.translation import gettext_lazy as _
from django.db.utils import OperationalError
from ajax_select.fields import AutoCompleteSelectField, AutoCompleteSelectMultipleField
from django_countries import countries

from alessandria.models import (
    GeneralConfiguration, ReaderBorrow, Reader, Author, Publisher, Book, BookAudience, BookCopy
)


max_borrow_days = 0
default_country = None
try:
    if GeneralConfiguration.objects.first() is not None:
        max_borrow_days = GeneralConfiguration.objects.first().max_borrow_days
except OperationalError:
    # To prevent "django.db.utils.OperationalError" when reseting the DB
    pass

_l_countries = sorted(dict(countries).items())
_l_default_exclude_fields = ['created_by', 'created_on', 'modified_by', 'modified_on']
_css_class_required_field = 'required'


class CommonForm(forms.ModelForm):
    required_css_class = 'required'  # Used in the template


class ReaderBorrowForm(CommonForm):
    class Meta:
        model = ReaderBorrow
        exclude = _l_default_exclude_fields
    borrowed_date = forms.DateField(
        label=Meta.model._meta.get_field('borrowed_date').verbose_name,
        initial=datetime.date.today()
    )
    borrow_due_date = forms.DateField(
        label=Meta.model._meta.get_field('borrow_due_date').verbose_name,
        initial=datetime.date.today() + datetime.timedelta(days=max_borrow_days)
    )

    # 'bookcopy_list' and 'reader_list' are registered lookups.py
    bookcopy = AutoCompleteSelectField(
        'bookcopy_list', label=Meta.model._meta.get_field('bookcopy').verbose_name,
        required=False, help_text=None, plugin_options={'autoFocus': True, 'minLength': 3}
    )
    reader = AutoCompleteSelectField(
        'reader_list', label=Meta.model._meta.get_field('reader').verbose_name,
        required=False, help_text=None, plugin_options={'autoFocus': True, 'minLength': 3}
    )

    def clean_reader(self):
        if self.cleaned_data['reader'] is None:
            raise forms.ValidationError(_("Please select a reader"))
        return self.cleaned_data['reader']

    def clean_bookcopy(self):
        bookcopy = self.cleaned_data['bookcopy']
        if bookcopy is None:
            raise forms.ValidationError(_("Please select a a book copy"))
        # Make sure this bookcopy was not already borrowed by somebody else
        already_borrowed = ReaderBorrow.objects.filter(bookcopy=bookcopy).filter(returned_on=None).first()
        error = False
        if already_borrowed is not None:
            if self.instance is not None:  # Update mode
                if already_borrowed.id != self.instance.id:  # Not updating the current record
                    error = True
            else:  # Create mode
                error = True
            if error:
                raise forms.ValidationError(
                    _('This book copy was already borrowed by {0}.').format(already_borrowed.reader)
                )
        return bookcopy


class ReaderForm(CommonForm):
    class Meta:
        model = Reader
        exclude = _l_default_exclude_fields + ['number', 'disabled_on']

    addr1 = forms.CharField(
        label=Meta.model._meta.get_field('addr1').verbose_name,
        widget=forms.TextInput(attrs={'size': '50'})
    )
    addr2 = forms.CharField(
        label=Meta.model._meta.get_field('addr2').verbose_name,
        widget=forms.TextInput(attrs={'size': '50'}),
        required=False
    )
       
    def clean(self):
        cleaned_data = super().clean()

        homonyms = Reader.objects.filter(
            first_name__iexact=cleaned_data.get("first_name")
        ).filter(
            last_name__iexact=cleaned_data.get("last_name")
        ).filter(
            birthday=cleaned_data.get("birthday")
        ).filter(
            city__iexact=cleaned_data.get("city")
        ).exclude(
            id=self.instance.id
        )
        if homonyms.exists():
            self.add_error('last_name', _("This reader already exists."))


class ReaderSearchForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Override the fields making it NOT mandatory
        self.fields['last_name'].required = False

    reader_enabled = forms.BooleanField(label=_("Readers enabled"), initial=True, required=False)

    class Meta:
        model = Reader
        fields = ('last_name',)


class ReaderEnableDisableForm(CommonForm):
    class Meta:
        model = Reader
        fields = ()


class AuthorForm(CommonForm):
    class Meta:
        model = Author
        exclude = _l_default_exclude_fields + ['is_isbn_import', 'import_source']

    def clean(self):
        cleaned_data = super().clean()

        homonyms = Author.objects.filter(
            first_name__iexact=cleaned_data.get("first_name")
        ).filter(
            last_name__iexact=cleaned_data.get("last_name")
        ).filter(
            birthday=cleaned_data.get("birthday")
        ).exclude(
            id=self.instance.id
        )
        if homonyms.exists():
            self.add_error('last_name', _("This author already exists."))


class AuthorSearchForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('last_name',)


class PublisherForm(CommonForm):
    class Meta:
        model = Publisher
        exclude = _l_default_exclude_fields + ['is_isbn_import', 'import_source']

    def clean(self):
        cleaned_data = super().clean()

        if Publisher.objects.filter(name__iexact=cleaned_data.get("name")).exclude(id=self.instance.id).exists():
            self.add_error('name', _("This publisher already exists."))


class PublisherSearchForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ('name',)


class BookForm(CommonForm):

    class Meta:
        model = Book
        exclude = _l_default_exclude_fields + ['related_to', 'cover_pic']

    title = forms.CharField(
        label=Meta.model._meta.get_field('title').verbose_name,
        widget=forms.TextInput(attrs={'size': '40'})
    )

    # 'author_list' and 'publisher_list' are registered lookups.py
    authors = AutoCompleteSelectMultipleField(
        'author_list', label=Meta.model._meta.get_field('authors').verbose_name,
        required=False, help_text=None, plugin_options={'autoFocus': True, 'minLength': 3}
    )
    publishers = AutoCompleteSelectMultipleField(
        'publisher_list', label=Meta.model._meta.get_field('publishers').verbose_name,
        required=False, help_text=None, plugin_options={'autoFocus': True, 'minLength': 3}
    )
    audiences = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(), label=Meta.model._meta.get_field('audiences').verbose_name,
        queryset=BookAudience.objects.all()
    )

    def clean_authors(self):
        if not any(self.cleaned_data['authors']):  # It is a list
            raise forms.ValidationError(_("Please select at least one author"))
        return self.cleaned_data['authors']

    def clean_publishers(self):
        if not any(self.cleaned_data['publishers']):  # It is a list
            raise forms.ValidationError(_("Please select at least one publisher"))
        return self.cleaned_data['publishers']


class BookSearchForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Override the fields making it NOT mandatory (these fields come from the model)
        self.fields['isbn_nb'].required = False
        self.fields['title'].required = False
        self.fields['category'].required = False

    author_name = forms.CharField(label=_('Author'), required=False)
    never_borrowed = forms.BooleanField(label=_('Never borrowed'), initial=False, required=False)

    class Meta:
        model = Book
        fields = ('isbn_nb', 'title', 'category', 'sub_category',)


class BookNoSearchForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Book
        fields = ()


class BookCopyForm(CommonForm):
    class Meta:
        model = BookCopy
        exclude = _l_default_exclude_fields + ['number', 'book', 'disabled_on']

    registered_on = forms.DateField(
        label=Meta.model._meta.get_field('registered_on').verbose_name, initial=datetime.date.today
    )


class BookCopyDisableForm(CommonForm):
    class Meta:
        model = BookCopy
        fields = ('disabled_on',)

    disabled_on = forms.DateField(
        label=Meta.model._meta.get_field('disabled_on').verbose_name,
        required=True
    )


class StatisticsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        first_year = ReaderBorrow.objects.order_by('borrowed_date').first().borrowed_date.year
        year_choices = [(year, year) for year in range(first_year, datetime.date.today().year + 1)]
        self.fields['year'] = forms.IntegerField(
            widget=forms.Select(
                choices=year_choices
            ),
            required=True,
            label=_("Year")
        )


# Will be used to get statistics for a specific criteria (book, author...)
class StatisticsDetailForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('isbn_nb',)

    author_name = forms.CharField(label=_('Author'), required=False)
    # Add the dates here

django-alessandria/alessandria/templates/alessandria/_inc_form_edit_footer.html
{% load i18n %}
{% if form.instance.id > 0 %}
  <div>{% trans "Created on" %} {{ form.instance.created_on }} {% trans "by" %} {{ form.instance.created_by.get_full_name }}</div>
  {% if form.instance.modified_by %}
    <div>{% trans "Updated on" %} {{ form.instance.modified_on }} {% trans "by" %} {{ form.instance.modified_by.get_full_name }}</div>
  {% endif %}
{% endif %}

django-alessandria/alessandria/templates/alessandria/author_list.html
{% extends 'alessandria/base_tpl.html' %}
{% load i18n %}

{% block title %}{% trans "Author list" %}{% endblock %}

{% block pageTitle %}{% trans "Author list" %}{% endblock %}

{% block content %}

<form class="form-horizontal" action="{% url 'alessandria:author_list' %}" method="post" role="form">{% csrf_token %}
  {% include 'alessandria/_inc_form_search_std.html' %}
</form>

<div class="row">
  <div class="col-md-12">
    {% include 'alessandria/_inc_paginator_list.html' %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th><a href="{% url 'alessandria:author_list' %}?order_field=last_name">{% trans "Name" %}</a></th>
          <th>Date de naissance</th>
          <th><a href="{% url 'alessandria:author_list' %}?order_field=created_on">{% trans "Created on" %}</a></th>
        </tr>
      </thead>
      <tbody>
        {% for author in object_list %}
          <tr>
              <td><a href="{% url 'alessandria:author_update' author.id %}">{{ author }}</a></td>
              <td>{{ author.birthday|default:"" }}</td>
              <td>{{ author.created_on }}</td>
          </tr>
        {% empty %}
          <tr><td colspan="3">{% trans "No author." %}</td></tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

django-alessandria/alessandria/templates/alessandria/base_tpl.html
{% load i18n %}
{% load static %}
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Alessandria">
    <meta name="author" content="Marc SCHNEIDER">
    <!--link rel="icon" href="../../favicon.ico" -->

    <title>{% block title %}Alessandria - {{ LIBRARY_NAME }}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'alessandria/layout/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'alessandria/layout/style.css' %}" />
    <link rel="stylesheet" href="{% static 'alessandria/layout/font-awesome/css/all.min.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
    <div class="container">
      <!-- Static navbar -->
      <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
        <a class="navbar-brand" href="{% url 'alessandria:home' %}">{% trans "Home" %}</a>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarBorrowings" data-toggle="dropdown">
              {% trans "Borrowings" %}
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'alessandria:reader_borrow_add' %}">{% trans "Add" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:reader_borrow_list' 'current' %}">{% trans "Current borrowings" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:reader_borrow_list' %}">{% trans "All borrowings" %}</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarBooks" data-toggle="dropdown">
              {% trans "Books" %}
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'alessandria:book_add' %}">{% trans "Add" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:book_isbn_import' %}">{% trans "ISBN import" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:book_list' %}">{% trans "List" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:book_no_copy_list' %}">{% trans "Without Book Copy" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:book_taken_away_list' %}">{% trans "Taken Away" %}</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarReaders" data-toggle="dropdown">
              {% trans "Readers" %}
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'alessandria:reader_add' %}">{% trans "Add" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:reader_list' %}">{% trans "List" %}</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarAuthors" data-toggle="dropdown">
              {% trans "Authors" %}
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'alessandria:author_add' %}">{% trans "Add" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:author_list' %}">{% trans "List" %}</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarPublishers" data-toggle="dropdown">
              {% trans "Publishers" %}
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'alessandria:publisher_add' %}">{% trans "Add" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:publisher_list' %}">{% trans "List" %}</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarStastics" data-toggle="dropdown">
              {% trans "Statistics" %}
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'alessandria:statistics_books_collections' %}">{% trans "Books Collections" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:statistics_readers' %}">{% trans "Readers" %}</a>
              <a class="dropdown-item" href="{% url 'alessandria:statistics_borrowings' %}">{% trans "Borrowings" %}</a>
            </div>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarHistory" data-toggle="dropdown">
                {% trans "History" %}
              </a>
              <div class="dropdown-menu">
                {% for item in request.session.user_nav_list %}
                  <a class="dropdown-item" href="{{ item.0 }}">{{ item.1 }}</a>
                {% endfor %}
              </div>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="/admin">{% trans "Administration" %}</a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'alessandria:logout' %}"><i class="fas fa-power-off"></i>&nbsp;{% trans "Log out" %} {{ user.first_name }}</a>
            {% else %}
              <a class="nav-link" href="{% url 'alessandria:login' %}">{% trans "Log in" %}</a>
            {% endif %}
          </li>
        </ul>
      </nav>

      <div class="container">
        <div class="card">
          <div class="card-header bg-card-header">
            <h3>{% block pageTitle %}Alessandria{% endblock %}</h3>
          </div>
          <div class="card-body">
            {% block content %}{% endblock %}
          </div>
        </div>
      </div>

    </div><!-- /.container -->

    <div align="center">
      Alessandria - Licence GNU GPLv3 - {{ VERSION|safe }} - {{ LIBRARY_NAME }}
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'alessandria/layout/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'alessandria/layout/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'alessandria/layout/bootstrap/js/bootstrap.min.js' %}"></script>
    {% block jscript %}{% endblock %}
  </body>
</html>

django-alessandria/alessandria/templates/alessandria/bookcopy_detail.html
{% extends 'alessandria/base_tpl.html' %}
{% load i18n %}
{% load tag_extras %}

{% block title %}{% trans "Book sample" %}{% endblock %}

{% block head %}
    <link rel="stylesheet" href="/static/alessandria/layout/bootstrap_datepicker/css/bootstrap-datepicker3.css">
{% endblock %}

{% block pageTitle %}{% trans "Book sample" %}:&nbsp;{{ form.instance.number|default:_("new") }} ({{ form.instance.book }}){% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-12">
    {% include 'alessandria/_inc_form_edit_header.html' %}
    {% if form.instance.is_disabled %}
        <div class="textInfo">{% trans "This sample was removed." %}</div>
    {% endif %}
    <div class="card">
      <div class="card-body">
        <form class="form-horizontal" action="" method="post" role="form">{% csrf_token %}
          {% for field in form %}
            <div class="form-group row">
              <label for="{{ field.id_for_label }}" class="col-sm-2 control-label {{ field.css_classes }}">{{ field.label }}</label>
              <div class="col-sm-10">
                {{ field|addcss:"form-control" }}
                {% if field.errors %}
                    <div class="text-danger">{{ field.errors }}</div>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          {% if form.instance.is_disabled %}
            <div class="form-group row">
              <label class="col-sm-2 control-label">{{ form.instance.disabled_on_label }}</label>
              <div class="col-sm-10">
                 {{ form.instance.disabled_on }}
              </div>
            </div>
          {% endif %}
          <div class="form-group row">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
              {% if form.instance.id > 0 %}
                {% if not form.instance.is_disabled %}
                  <a class="btn btn-warning" href="{% url 'alessandria:bookcopy_disable' form.instance.id %}">{% trans "Take out" %}</a>
                {% endif %}
                {% if not form.instance.was_borrowed %}
                  <a class="btn btn-danger" href="{% url 'alessandria:bookcopy_delete' form.instance.id %}">{% trans "Delete" %}</a>
                {% endif %}
              {% endif %}
              <a class="btn" href="{% url 'alessandria:book_update' form.instance.book.id %}">{% trans "Cancel" %}</a>
            </div>
          </div>
        </form>
        {% include 'alessandria/_inc_form_edit_footer.html' %}
      </div>
    </div>
  </div><!-- /.col-sm- -->
</div>
{% endblock %}

{% block jscript %}
<script type="text/javascript" src="/static/alessandria/layout/jquery-ui/jquery-ui.min.js"></script>
<script src="/static/alessandria/layout/bootstrap_datepicker/js/bootstrap-datepicker.min.js"></script>
<script src="/static/alessandria/layout/bootstrap_datepicker/locales/bootstrap-datepicker.fr.min.js"></script>
<script>
  {% get_current_language as LANGUAGE_CODE %}
  $(function() {
    $('#id_registered_on').datepicker({
      language: "{{ LANGUAGE_CODE }}",
      autoclose: true,
      todayHighlight: true,
    });
    $('#id_price_date').datepicker({
      language: "{{ LANGUAGE_CODE }}",
      autoclose: true,
      todayHighlight: true,
    });
  });
</script>
{% endblock %}

django-alessandria/alessandria/templates/alessandria/reader_borrow_list.html
{% extends 'alessandria/base_tpl.html' %}
{% load i18n %}

{% block title %}{{ page_title }}{% endblock %}

{% block pageTitle %}{{ page_title }}{% endblock %}

{% block content %}
<div class="row-fluid">
  <div class="span12">
    {% include 'alessandria/_inc_paginator_list.html' %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th><a href="{% url 'alessandria:reader_borrow_list' display %}?order_field=borrowed_date">{% trans "Borrowed on" %}</a></th>
          <th><a href="{% url 'alessandria:reader_borrow_list' display %}?order_field=reader__last_name">{% trans "Reader" %}</a></th>
          <th><a href="{% url 'alessandria:reader_borrow_list' display %}?order_field=bookcopy__book__title">{% trans "Book" %}</a></th>
          <th><a href="{% url 'alessandria:reader_borrow_list' display %}?order_field=borrow_due_date">{% trans "Due date" %}</a></th>
          <th><a href="{% url 'alessandria:reader_borrow_list' display %}?order_field=returned_on">{% trans "Returned on" %}</a></th>
        </tr>
      </thead>
      <tbody>
      {% for borrow in object_list %}
        <tr>
          <td>
            {% if borrow.is_late %}
            <button type="button" class="btn btn-default" aria-label="{% trans "Late" %}">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            </button>
            {% endif %}
          </td>
          <td><a href="{% url 'alessandria:reader_borrow_update' borrow.id %}">{{ borrow.borrowed_date|date:"SHORT_DATE_FORMAT" }}</a></td>
          <td><a href="{% url 'alessandria:reader_update' borrow.reader.id %}">{{ borrow.reader }}</a></td>
          <td><a href="{% url 'alessandria:book_update' borrow.bookcopy.book.id %}">{{ borrow.bookcopy.book }}</a></td>
          <td>{{ borrow.borrow_due_date|date:"SHORT_DATE_FORMAT" }}</td>
          <td>{{ borrow.returned_on|default:"" }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">{% trans "No borrowing." %}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}